# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do inverse of sysmetric matrix 
#' @param Min A sysmetric matrix
#' 
#' @return A list
#' 
#' @export
SysMatEigen3 <- function(M) {
    .Call(`_spatialDEG_SysMatEigen3`, M)
}

#' Do inverse of sysmetric matrix 
#' @param Min A sysmetric matrix
#' 
#' @return A list
#' 
#' @export
SysMatEigen2 <- function(M) {
    .Call(`_spatialDEG_SysMatEigen2`, M)
}

spatialDEG_true_kernel_test <- function(W, Y, K1, K2, Initial_theta, mu_fixed = TRUE, verbose = TRUE, check_positive = FALSE) {
    .Call(`_spatialDEG_spatialDEG_true_kernel_test`, W, Y, K1, K2, Initial_theta, mu_fixed, verbose, check_positive)
}

#' @author Yi Yang
#' @title
#' spatialDEG
#' @description
#' spatialDEG to perform differentially expressed gene analysis by leveraging spatial information.
#'
#' @param spa1  spatial location for the first dataset.
#' @param spa2  spatial location for the second dataset.
#' @param W  gene expression file with full name.
#' @param Y  covariates file for eQTL data.
#' @param Initial_theta  covariates file for GWAS data, e.g. top 10 PCs.
#' @param num_ls number of length scale and periodeirtor
#' @param interation The maximum iteration
#' @param Kernel_fixed logical value specifying the 
#' @param verbose logical value specifying the 
#' @param kernel_matched logical value specifying the 
#' @param coreNum Number of cores used for parallel computation
#' @param tol tolence to stop the algorithm
#'
#' @return List of model parameters
#'
#'
#' @details
#' \code{spatialDEG_paral_test} run spatialDEG model.
#' @export
spatialDEG_paral_test <- function(spa1, spa2, W, Y, Initial_theta, num_ls = 20L, iteration = 100L, Kernel_fixd = FALSE, verbose = FALSE, kernel_matched = FALSE, coreNum = 1L, tol = 0.0001) {
    .Call(`_spatialDEG_spatialDEG_paral_test`, spa1, spa2, W, Y, Initial_theta, num_ls, iteration, Kernel_fixd, verbose, kernel_matched, coreNum, tol)
}

spatialDEG_test <- function(spa1, spa2, W, Y, Initial_theta, mu_fixed = TRUE, verbose = TRUE) {
    .Call(`_spatialDEG_spatialDEG_test`, spa1, spa2, W, Y, Initial_theta, mu_fixed, verbose)
}

